version: "3.7"
services:
  ifood_cadastro:
    container_name: ifood_cadastro
    image: postgres
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
      - "5432:5432"
    volumes:
      - /home/esiquielneto/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data

  ifood_marketplace:
    container_name: ifood_marketplace
    image: postgres
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - "5433:5432"
    volumes:
      - /home/esiquielneto/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data

  keycloak_ifood:
    container_name: keycloak_ifood
    image: quay.io/keycloak/keycloak
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - "8180:8080"

  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:1.29
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"

  prometheus_ifood:
    container_name: prometheus_ifood
    image: prometheus-ifood
    network_mode: "host"

  grafana_ifood:
    container_name: grafana_ifood
    image: grafana/grafana:8.3.4
    network_mode: "host"
