CREATE TABLE restaurante (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(255) NULL,
	proprietario varchar(255) NULL,
	cnpj varchar(255) NULL,
	datacriacao timestamp NULL,
	dataatualizacao timestamp NULL,
	localizacao_id int NULL,
	CONSTRAINT restaurante_pkey PRIMARY KEY (id)
);

ALTER TABLE restaurante ADD CONSTRAINT fk_restaurante_localizacao FOREIGN KEY (localizacao_id) REFERENCES localizacao(id);