CREATE TABLE prato (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nome varchar(255) NULL,
	descricao varchar(255) NULL,
	preco numeric(19,2) NULL,
	restaurante_id int NULL,
	CONSTRAINT prato_pkey PRIMARY KEY (id)
);

ALTER TABLE prato ADD CONSTRAINT fk_prato_restaurante FOREIGN KEY (restaurante_id) REFERENCES restaurante(id);